name: mi
channels:
  - defaults
dependencies:
  - anyio=4.6.2=py312hca03da5_0
  - appnope=0.1.3=py312hca03da5_1001
  - argon2-cffi=21.3.0=pyhd3eb1b0_0
  - argon2-cffi-bindings=21.2.0=py312h80987f9_1
  - asttokens=2.0.5=pyhd3eb1b0_0
  - async-lru=2.0.4=py312hca03da5_0
  - attrs=24.3.0=py312hca03da5_0
  - babel=2.11.0=py312hca03da5_0
  - beautifulsoup4=4.12.3=py312hca03da5_0
  - bleach=6.2.0=py312hca03da5_0
  - brotli-python=1.0.9=py312h313beb8_9
  - bzip2=1.0.8=h80987f9_6
  - c-ares=1.19.1=h80987f9_0
  - ca-certificates=2024.12.31=hca03da5_0
  - certifi=2024.12.14=py312hca03da5_0
  - cffi=1.17.1=py312h3eb5a62_1
  - comm=0.2.1=py312hca03da5_0
  - cyrus-sasl=2.1.28=h9131b1a_1
  - debugpy=1.8.11=py312h313beb8_0
  - decorator=5.1.1=pyhd3eb1b0_0
  - defusedxml=0.7.1=pyhd3eb1b0_0
  - executing=0.8.3=pyhd3eb1b0_0
  - expat=2.6.4=h313beb8_0
  - gettext=0.21.0=hbdbcc25_2
  - glib=2.78.4=h313beb8_0
  - glib-tools=2.78.4=h313beb8_0
  - gst-plugins-base=1.14.1=h313beb8_1
  - gstreamer=1.14.1=h80987f9_1
  - h11=0.14.0=py312hca03da5_0
  - httpcore=1.0.2=py312hca03da5_0
  - httpx=0.27.0=py312hca03da5_0
  - icu=73.1=h313beb8_0
  - ipykernel=6.29.5=py312hca03da5_0
  - ipython=8.30.0=py312hca03da5_0
  - ipywidgets=8.1.5=py312hca03da5_0
  - jedi=0.19.2=py312hca03da5_0
  - jinja2=3.1.4=py312hca03da5_1
  - jpeg=9e=h80987f9_3
  - json5=0.9.25=py312hca03da5_0
  - jsonschema=4.23.0=py312hca03da5_0
  - jupyter=1.0.0=py312hca03da5_9
  - jupyter-lsp=2.2.0=py312hca03da5_0
  - jupyter_client=8.6.0=py312hca03da5_0
  - jupyter_console=6.6.3=py312hca03da5_1
  - jupyter_core=5.7.2=py312hca03da5_0
  - jupyter_events=0.10.0=py312hca03da5_0
  - jupyter_server=2.14.1=py312hca03da5_0
  - jupyter_server_terminals=0.4.4=py312hca03da5_1
  - jupyterlab=4.2.5=py312hca03da5_0
  - jupyterlab_pygments=0.1.2=py_0
  - jupyterlab_server=2.27.3=py312hca03da5_0
  - jupyterlab_widgets=3.0.13=py312hca03da5_0
  - krb5=1.20.1=hf3e1bf2_1
  - libabseil=20240116.2=cxx17_h313beb8_0
  - libclang=14.0.6=default_h1b80db6_2
  - libclang13=14.0.6=default_h24352ff_2
  - libcurl=8.11.1=hde089ae_0
  - libcxx=14.0.6=h848a8c0_0
  - libedit=3.1.20230828=h80987f9_0
  - libev=4.33=h1a28f6b_1
  - libffi=3.4.4=hca03da5_1
  - libglib=2.78.4=h0a96307_0
  - libiconv=1.16=h80987f9_3
  - libllvm14=14.0.6=h19fdd8a_4
  - libmpdec=4.0.0=h80987f9_0
  - libnghttp2=1.57.0=h62f6fdd_0
  - libpng=1.6.39=h80987f9_0
  - libpq=17.2=h02f6b3c_0
  - libprotobuf=4.25.3=h514c7bf_0
  - libsodium=1.0.18=h1a28f6b_0
  - libssh2=1.11.1=h3e2b118_0
  - libxml2=2.13.5=h0b34f26_0
  - llvm-openmp=14.0.6=hc6e5704_0
  - lz4-c=1.9.4=h313beb8_1
  - markupsafe=2.1.3=py312h80987f9_1
  - matplotlib-inline=0.1.6=py312hca03da5_0
  - mistune=2.0.4=py312hca03da5_0
  - mysql=8.4.0=h3a6587f_1
  - nbclient=0.8.0=py312hca03da5_0
  - nbconvert=7.16.4=py312hca03da5_0
  - nbformat=5.10.4=py312hca03da5_0
  - ncurses=6.4=h313beb8_0
  - nest-asyncio=1.6.0=py312hca03da5_0
  - notebook=7.2.2=py312hca03da5_1
  - notebook-shim=0.2.3=py312hca03da5_0
  - openldap=2.6.4=he7ef289_0
  - openssl=3.0.15=h80987f9_0
  - overrides=7.4.0=py312hca03da5_0
  - packaging=24.2=py312hca03da5_0
  - pandocfilters=1.5.0=pyhd3eb1b0_0
  - parso=0.8.4=py312hca03da5_0
  - pcre2=10.42=hb066dcc_1
  - pexpect=4.8.0=pyhd3eb1b0_3
  - pip=24.2=py312hca03da5_0
  - platformdirs=3.10.0=py312hca03da5_0
  - ply=3.11=py312hca03da5_1
  - prometheus_client=0.21.0=py312hca03da5_0
  - prompt-toolkit=3.0.43=py312hca03da5_0
  - prompt_toolkit=3.0.43=hd3eb1b0_0
  - psutil=5.9.0=py312h80987f9_1
  - ptyprocess=0.7.0=pyhd3eb1b0_2
  - pure_eval=0.2.2=pyhd3eb1b0_0
  - pygments=2.15.1=py312hca03da5_1
  - pyqt=5.15.10=py312h313beb8_0
  - pyqt5-sip=12.13.0=py312h80987f9_0
  - pysocks=1.7.1=py312hca03da5_0
  - python=3.12.8=h99e199e_0
  - python-dateutil=2.9.0post0=py312hca03da5_2
  - python-fastjsonschema=2.20.0=py312hca03da5_0
  - python-json-logger=3.2.1=py312hca03da5_0
  - pyyaml=6.0.2=py312h80987f9_0
  - pyzmq=26.2.0=py312h313beb8_0
  - qt-main=5.15.2=h0917680_11
  - qtconsole=5.6.0=py312hca03da5_0
  - qtpy=2.4.1=py312hca03da5_0
  - readline=8.2=h1a28f6b_0
  - requests=2.32.3=py312hca03da5_1
  - rfc3339-validator=0.1.4=py312hca03da5_0
  - rfc3986-validator=0.1.1=py312hca03da5_0
  - rpds-py=0.22.3=py312h2aea54e_0
  - send2trash=1.8.2=py312hca03da5_1
  - setuptools=75.1.0=py312hca03da5_0
  - sip=6.7.12=py312h313beb8_1
  - sniffio=1.3.0=py312hca03da5_0
  - soupsieve=2.5=py312hca03da5_0
  - sqlite=3.45.3=h80987f9_0
  - stack_data=0.2.0=pyhd3eb1b0_0
  - terminado=0.17.1=py312hca03da5_0
  - tinycss2=1.2.1=py312hca03da5_0
  - tk=8.6.14=h6ba3021_0
  - tornado=6.4.2=py312h80987f9_0
  - traitlets=5.14.3=py312hca03da5_0
  - typing-extensions=4.12.2=py312hca03da5_0
  - typing_extensions=4.12.2=py312hca03da5_0
  - wcwidth=0.2.5=pyhd3eb1b0_0
  - webencodings=0.5.1=py312hca03da5_2
  - websocket-client=1.8.0=py312hca03da5_0
  - wheel=0.44.0=py312hca03da5_0
  - widgetsnbextension=4.0.13=py312hca03da5_0
  - xz=5.4.6=h80987f9_1
  - yaml=0.2.5=h1a28f6b_0
  - zeromq=4.3.5=h313beb8_0
  - zlib=1.2.13=h18a0788_1
  - zstd=1.5.6=hfb09047_0
  - pip:
      - aioitertools==0.12.0
      - annotated-types==0.7.0
      - bcrypt==4.2.1
      - boto3==1.35.97
      - botocore==1.35.97
      - charset-normalizer==3.4.1
      - colorama==0.4.6
      - contourpy==1.3.1
      - cryptography==44.0.0
      - cycler==0.12.1
      - deprecated==1.2.15
      - dill==0.3.9
      - dlhub-sdk==2.1.0
      - dnspython==2.7.0
      - emmet-core==0.84.6rc3
      - et-xmlfile==2.0.0
      - fair-research-login==0.3.1
      - fonttools==4.55.3
      - foundry-ml==1.0.4
      - globus-compute-common==0.5.0
      - globus-compute-sdk==2.34.0
      - globus-sdk==3.49.0
      - h5py==3.12.1
      - idna==3.10
      - jmespath==1.0.1
      - joblib==1.4.2
      - json2table==1.1.5
      - jsonlines==4.0.0
      - jsonschema-specifications==2024.10.1
      - kiwisolver==1.4.8
      - latexcodec==3.0.0
      - maggma==0.71.1
      - markdown-it-py==3.0.0
      - matplotlib==3.10.0
      - mdf-connect-client==0.5.0
      - mdf-forge==0.8.0
      - mdf-toolbox==0.7.1
      - mdurl==0.1.2
      - mongomock==4.3.0
      - monty==2025.1.9
      - mp-api==0.45.1
      - mpmath==1.3.0
      - msgpack==1.1.0
      - nameparser==1.1.3
      - networkx==3.4.2
      - numpy==1.26.4
      - openpyxl==3.1.5
      - orjson==3.10.14
      - palettable==3.3.3
      - pandas==2.2.3
      - paramiko==3.5.0
      - pika==1.3.2
      - pillow==11.1.0
      - plotly==5.24.1
      - pybtex==0.24.0
      - pycparser==2.22
      - pydantic==2.10.5
      - pydantic-core==2.27.2
      - pydantic-settings==2.7.1
      - pydash==8.0.4
      - pygithub==2.5.0
      - pyjwt==2.10.1
      - pymatgen==2025.1.9
      - pymongo==4.10.1
      - pynacl==1.5.0
      - pyparsing==3.2.1
      - python-dotenv==1.0.1
      - pytz==2024.2
      - referencing==0.35.1
      - rich==13.7.1
      - ruamel-yaml==0.18.10
      - ruamel-yaml-clib==0.2.12
      - s3transfer==0.10.4
      - scipy==1.15.1
      - sentinels==1.0.0
      - six==1.17.0
      - smart-open==7.1.0
      - spglib==2.5.0
      - sshtunnel==0.4.0
      - sympy==1.13.3
      - tabulate==0.9.0
      - tblib==1.7.0
      - tenacity==9.0.0
      - texttable==1.7.0
      - tqdm==4.67.1
      - tzdata==2024.2
      - uncertainties==3.2.2
      - urllib3==2.3.0
      - wrapt==1.17.1
prefix: /Users/ramseyissa/miniconda3/envs/mi
